export const skillset = [
  "Javascript ES6+",
  "Debugging",
  "Git",
  "React",
  "Semantic & Accesible HTML",
  "Teamwork",
  "React Context",
  "Responsive Web Design",
  "HTML, CSS",
  "API",
  "Web Standards",
  "Redux",
  "Tailwind",
  "Vue",
  "Vitest",
  "Pinia",
  "Typescript (basic knowledge)",
];
