export const skillset = [
  "Javascript ES6+",
  "API (fetch, axios)",
  "Promises, Async/Await",
  "Immutability",
  "Error handling",
  "React",
  "React hooks",
  "React Router",
  "Semantic & accesible HTML",
  "Responsive Web Design",
  "CSS Flexbox and Grid",
  "CSS BEM convention",
  "Git",
  "Github Pull Requests & Review",
  "Redux, Redux-Saga, Redux Toolkit",
  "NPM",
  "Scrum",
  "Trello",
  "Teamwork",
  "Markdown",
];
