export const skillset = [
  "React",
  "Vue",
  "Angular",
  "Pinia",
  "Redux",
  "REST API",
  "GraphQL",
  "JavaScript ES6+",
  "TypeScript",
  "Semantic & Accesible HTML",
  "HTML5",
  "CSS3",
  "Responsive Web Design",
  "Web Standards",
  "Tailwind",
  "Bootstrap",
  "Styled Components",
  "Git",
  "Figma",
  "Problem-Solving",
  "Teamwork",
  "SASS",
];
